repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.11.1
  hooks:
    - id: uv-lock
- repo: https://github.com/asottile/pyupgrade
  rev: v3.21.2
  hooks:
    - id: pyupgrade
      args: [--py310-plus]
      files: '^(.*/)?.*\.py$'
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.7
  hooks:
    - id: ruff-check
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
